# How many except statements can a try-except block have? Name Some built-in exception classes:.





# try:


#     s1 = int(input("Enter the valu s1 :"))
#     s2 = int(input("Enter the value s2 :"))

#     s3 = s1/s2


# except ZeroDivisionError:

#     print(s3)




# try:
#     # Code that might raise multiple exceptions
#     x = int(input("Enter a number: "))
#     result = 10 / x
#     data = [1, 2, 3]
#     print(data[x])
# except ValueError:
#     print("Invalid input! Please enter a valid number.")
# except ZeroDivisionError:
#     print("Error! Division by zero is not allowed.")
# except IndexError:
#     print("Error! Index out of range.")
# except Exception as e:
#     print(f"An unexpected error occurred: {e}")








s1 = 10+20

s2 = 9+3



print("Hello word")


print(s1)


try:


    print(s1+s3)



except:


    print("Error")


    print(s2)